-- Splitwise-Lite — initial schema.
-- Portable SQL: runs unchanged on PostgreSQL 14+ and H2 2.x in PostgreSQL mode.
-- All monetary values are stored as integer cents (BIGINT) to avoid floating-point drift.

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    display_name    VARCHAR(100) NOT NULL,
    password_hash   VARCHAR(100) NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE expense_groups (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    currency_code   VARCHAR(3)   NOT NULL DEFAULT 'INR',
    created_by      BIGINT       NOT NULL REFERENCES users(id),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_expense_groups_created_by ON expense_groups (created_by);

CREATE TABLE group_members (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT       NOT NULL REFERENCES expense_groups(id) ON DELETE CASCADE,
    user_id     BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role        VARCHAR(20)  NOT NULL DEFAULT 'MEMBER',
    joined_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_group_members_group_user UNIQUE (group_id, user_id)
);
CREATE INDEX idx_group_members_group_id ON group_members (group_id);
CREATE INDEX idx_group_members_user_id  ON group_members (user_id);

CREATE TABLE expenses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT       NOT NULL REFERENCES expense_groups(id) ON DELETE CASCADE,
    payer_id        BIGINT       NOT NULL REFERENCES users(id),
    description     VARCHAR(255) NOT NULL,
    amount_cents    BIGINT       NOT NULL CHECK (amount_cents > 0),
    currency_code   VARCHAR(3)   NOT NULL,
    split_type      VARCHAR(20)  NOT NULL,
    occurred_at     TIMESTAMP    NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_expenses_group_id ON expenses (group_id);
CREATE INDEX idx_expenses_payer_id ON expenses (payer_id);

CREATE TABLE expense_shares (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id      BIGINT NOT NULL REFERENCES expenses(id) ON DELETE CASCADE,
    user_id         BIGINT NOT NULL REFERENCES users(id),
    share_cents     BIGINT NOT NULL CHECK (share_cents >= 0),
    CONSTRAINT uq_expense_shares_expense_user UNIQUE (expense_id, user_id)
);
CREATE INDEX idx_expense_shares_expense_id ON expense_shares (expense_id);
CREATE INDEX idx_expense_shares_user_id    ON expense_shares (user_id);

CREATE TABLE settlements (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT       NOT NULL REFERENCES expense_groups(id) ON DELETE CASCADE,
    from_user_id    BIGINT       NOT NULL REFERENCES users(id),
    to_user_id      BIGINT       NOT NULL REFERENCES users(id),
    amount_cents    BIGINT       NOT NULL CHECK (amount_cents > 0),
    currency_code   VARCHAR(3)   NOT NULL,
    note            VARCHAR(255),
    settled_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_settlements_distinct CHECK (from_user_id <> to_user_id)
);
CREATE INDEX idx_settlements_group_id      ON settlements (group_id);
CREATE INDEX idx_settlements_from_user_id  ON settlements (from_user_id);
CREATE INDEX idx_settlements_to_user_id    ON settlements (to_user_id);
